apiVersion: v1
kind: Secret
metadata:
  name: <product name here (ideaiu or webstorm)>-offline-activation-code
  labels:
    app.kubernetes.io/component: workspace-secret
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/automount-workspace-secret: 'false'
    che.eclipse.org/mount-path: /tmp/
    che.eclipse.org/mount-as: file
data:
  <product name here (ideaIU or WebStorm)>.key: <base64 encoded data content here>
