#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

on:
  push:
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - '**/.gitignore'
      - '**/doc/**'
      - '**/devfiles/**'
      - '**/kubernetes/**'
      - '/run-container*.sh'
    branches: [ master ]
  
jobs:
  prepare:
    name: Prepare Environment
    runs-on: ubuntu-18.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::{\"include\":[$( .github/build-container-matrix.sh -m all )]}"
  build:
    name: ${{ matrix.displayName }} (${{ matrix.imageTag }}) - Projector Docker Build and Publish to Quay.io
    needs: prepare
    runs-on: ubuntu-18.04
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Clone source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Clone projector sources
        run: |
          ./clone-projector.sh
      - name: Docker image build and publish
        run: |
          ./build-container.sh ${{ matrix.imageName }}:${{ matrix.imageTag }} ${{ matrix.downloadUrl }}
          docker push ${{ matrix.imageName }}:${{ matrix.imageTag }}
